### ISSUE TITLE
New uncaptured string

### ISSUE THREAD

**Issue by kazerniel** [kevinpetit/legacy-chatfilter#72]
![image](https://user-images.githubusercontent.com/5689996/167328915-b231da64-32d4-4dea-8c63-105363c72324.png)

**Comment by BearsMan** [comment]
I'll fix the string codes tomorrow when I get around to it

**Comment by kazerniel** [comment]
Wow quick response :)

Was about to edit the post to add that it seems like this string: `MM0GAMÉRSMaRKÉT"C"0"M`

**Comment by BearsMan** [comment]
Yep I'll update it the string in note pad and set a PR

**Comment by BearsMan** [comment]
This has been fixed and is ready closing
